version: '3.9'
services:
  discovery-server:
    image: discovery-server:latest
    build: ./discovery-server
    ports:
      - "8761:8761"

  kitchen-service:
    image: kitchen-service:latest
    build: ./kitchen
    depends_on:
      - discovery-server
      - yb-master-1
      - yb-tserver-1
    environment:
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8761
      - DB_URL=${DB_URL:-jdbc:postgresql://host.docker.internal:5433/yugabyte}
      - DB_USER=${DB_USER:-yugabyte}
      - DB_PASSWORD=${DB_PASSWORD:-yugabyte}
      
  tracker-service:
    image: tracker-service:latest
    build: ./tracker
    depends_on:
      - discovery-server
    environment:
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8761
      - DB_URL=${DB_URL:-jdbc:postgresql://host.docker.internal:5433/yugabyte}
      - DB_USER=${DB_USER:-yugabyte}
      - DB_PASSWORD=${DB_PASSWORD:-yugabyte}
    
  api-gateway:
    image: api-gateway:latest
    build: ./api-gateway
    depends_on:
      - discovery-server
    ports:
      - "8080:8080"
    environment:
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8761  
